# Generated by Django 3.2.5 on 2021-07-16 18:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='user', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('userRole', models.CharField(default='Patient', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveSmallIntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalLocation', models.TextField()),
                ('bookedSlot', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None), size=48)),
                ('patientID', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None), size=48)),
                ('bookingType', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=48)),
            ],
            bases=('User.user', models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('medicalHistory', models.TextField()),
            ],
            bases=('User.user', models.Model),
        ),
    ]
