# Generated by Django 3.2.5 on 2021-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userRole',
        ),
        migrations.AddField(
            model_name='users',
            name='isDoctor',
            field=models.BooleanField(default=True),
        ),
    ]
