# Generated by Django 3.2.5 on 2021-07-17 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210717_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bookedSlot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=48),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bookingType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=48),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patientID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=48),
        ),
    ]
