# Generated by Django 3.2.5 on 2021-07-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210717_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bookedSlot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bookingType',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patientID',
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=-1)),
                ('type', models.BooleanField(default=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('pat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
    ]
